version: '2'

services:
  7daystodie:
#    image: didstopia/base:nodejs-steamcmd-ubuntu-16.04
    image: didstopia/7dtd-server:latest
    entrypoint: ./start.sh
#    args:
#      - DEBIAN_FRONTEND=noninteractive
    environment:
      - SEVEN_DAYS_TO_DIE_TELNET_PORT=8081
      - SEVEN_DAYS_TO_DIE_START_MODE=0 #0 install and update and start, 1 install and update, 2 install without update and start
      - SEVEN_DAYS_TO_DIE_UPDATE_BRANCH=public
      - SEVEN_DAYS_TO_DIE_SERVER_STARTUP_ARGUMENTS=-configfile=server_data/serverconfig.xml -logfile /steamcmd/7dtd/log/output.log -quit -batchmode -nographics -dedicated

